/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 *
 * $Revision: 4127$
 * $Date: 2009-06-17$
 */

#ifndef SVNREH_H
#define SVNREV_H

#define SVN_REV		4127
#define SVN_REVSTR	"4127"
#define SVN_REVDATE	"2009-06-17"
#define SVN_REVSTAMP	20090617L
#define SVN_MODIFIED	0

#endif /* SVNREV_H */
